In [1]:
import pandas as pd

cencus = pd.read_csv('india_census_housing-hlpca-full.csv')
cencus.head()

,State Code,State Name,District Code,District Name,Tehsil Code,Tehsil Name,Town Code/Village code,Ward No,Area Name,Rural/Urban,...,Contition_T_Total,Contition_T_Good,Contition_T_Livable,Contition_T_Dilapidated,Contition_R_Total,Residence_Good,Residence_Livable,Residence_Dilapidated,Residence_cum_other,Residence_cum_Good
0,1,JAMMU & KASHMIR,1,Kupwara,0,Kupwara,0,0,District - Kupwara,Rural,...,100,33.6,58.1,8.3,90.9,32.7,51.0,7.2,9.1,1.0
1,1,JAMMU & KASHMIR,1,Kupwara,0,Kupwara,0,0,District - Kupwara,Total,...,100,34.8,57.3,7.9,91.0,33.8,50.2,6.9,9.0,0.9
2,1,JAMMU & KASHMIR,1,Kupwara,0,Kupwara,0,0,District - Kupwara,Urban,...,100,45.7,49.5,4.8,91.8,45.0,42.2,4.5,8.2,0.7
3,1,JAMMU & KASHMIR,2,Badgam,0,Badgam,0,0,District - Badgam,Rural,...,100,49.7,46.3,3.9,97.2,49.0,44.5,3.7,2.8,0.7
4,1,JAMMU & KASHMIR,2,Badgam,0,Badgam,0,0,District - Badgam,Total,...,100,51.6,44.7,3.8,97.3,50.8,43.0,3.5,2.7,0.8

In [2]:
langlant = pd.read_csv('district wise centroids.csv')
langlant.head()

                 State         District   Latitude  Longitude
0  Andaman and Nicobar  Andaman Islands  12.382571  92.822911
1  Andaman and Nicobar  Nicobar Islands   7.835291  93.511601
2       Andhra Pradesh         Adilabad  19.284514  78.813212
3       Andhra Pradesh        Anantapur  14.312066  77.460158
4       Andhra Pradesh         Chittoor  13.331093  78.927639

In [3]:
final_df = langlant.merge(cencus, left_on='District',right_on='District Name').drop(columns=['District Name','State Name'])
final_df.to_csv('final.csv', index=False)

In [ ]:
final_csv = pd.read_csv('final.csv')
pop = pd.read_csv('population.csv')
final_csv = final_df.merge(pop, left_on='District',right_on='District')
final_csv = final_csv.drop_duplicates()
final_csv.to_csv('final_csv.csv', index=False)
final_csv.rename(columns={'Latitude_x': 'Latitude', 'Longitude_x': 'Longitude'}, inplace=True)
final_csv = dta_cleaned = final_csv.drop(final_csv.columns[1], axis=1)

NameError: name 'pop' is not defined

In [42]:
dta_cleaned = final_csv.loc[:, final_csv.columns != 'District code']

# Display the first few rows of the cleaned DataFrame
dta_cleaned.head()

,State_x,District,Latitude,Longitude,State Code,District Code,Tehsil Code,Tehsil Name,Town Code/Village code,Ward No,...,Contition_R_Total,Residence_Good,Residence_Livable,Residence_Dilapidated,Residence_cum_other,Residence_cum_Good,Population,Households_with_Internet,sex_ratio,literacy_rate
0,Andhra Pradesh,Adilabad,19.284514,78.813212,28,532,0,Adilabad,0,0,...,98.8,57.0,35.3,6.5,1.2,0.8,2741239,5512,100.0,54.0
1,Andhra Pradesh,Adilabad,19.284514,78.813212,28,532,0,Adilabad,0,0,...,98.6,61.2,31.9,5.5,1.4,0.9,2741239,5512,100.0,54.0
2,Andhra Pradesh,Adilabad,19.284514,78.813212,28,532,0,Adilabad,0,0,...,98.1,72.2,23.0,2.8,1.9,1.4,2741239,5512,100.0,54.0
3,Andhra Pradesh,Anantapur,14.312066,77.460158,28,553,0,Anantapur,0,0,...,97.6,73.6,21.0,2.9,2.4,1.7,4081148,8606,98.0,57.0
4,Andhra Pradesh,Anantapur,14.312066,77.460158,28,553,0,Anantapur,0,0,...,96.6,73.6,20.6,2.4,3.4,2.4,4081148,8606,98.0,57.0

In [43]:
final_csv.rename(columns={'State_x': 'State'}, inplace=True)
final_csv

,State,District,Latitude,Longitude,State Code,District Code,Tehsil Code,Tehsil Name,Town Code/Village code,Ward No,...,Residence_Good,Residence_Livable,Residence_Dilapidated,Residence_cum_other,Residence_cum_Good,District code,Population,Households_with_Internet,sex_ratio,literacy_rate
0,Andhra Pradesh,Adilabad,19.284514,78.813212,28,532,0,Adilabad,0,0,...,57.0,35.3,6.5,1.2,0.8,532,2741239,5512,100.0,54.0
1,Andhra Pradesh,Adilabad,19.284514,78.813212,28,532,0,Adilabad,0,0,...,61.2,31.9,5.5,1.4,0.9,532,2741239,5512,100.0,54.0
2,Andhra Pradesh,Adilabad,19.284514,78.813212,28,532,0,Adilabad,0,0,...,72.2,23.0,2.8,1.9,1.4,532,2741239,5512,100.0,54.0
3,Andhra Pradesh,Anantapur,14.312066,77.460158,28,553,0,Anantapur,0,0,...,73.6,21.0,2.9,2.4,1.7,553,4081148,8606,98.0,57.0
4,Andhra Pradesh,Anantapur,14.312066,77.460158,28,553,0,Anantapur,0,0,...,73.6,20.6,2.4,3.4,2.4,553,4081148,8606,98.0,57.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1702,West Bengal,Puruliya,23.254192,86.396853,19,340,0,Puruliya,0,0,...,30.7,55.5,6.9,6.9,1.7,340,2930115,3551,96.0,55.0
1703,West Bengal,Puruliya,23.254192,86.396853,19,340,0,Puruliya,0,0,...,47.9,41.4,6.5,4.2,2.0,340,2930115,3551,96.0,55.0
1704,West Bengal,Uttar Dinajpur,26.044619,88.235952,19,330,0,Uttar Dinajpur,0,0,...,29.1,56.1,12.1,2.7,0.7,330,3007134,2883,94.0,50.0
1705,West Bengal,Uttar Dinajpur,26.044619,88.235952,19,330,0,Uttar Dinajpur,0,0,...,30.8,54.1,12.4,2.7,0.8,330,3007134,2883,94.0,50.0
1706,West Bengal,Uttar Dinajpur,26.044619,88.235952,19,330,0,Uttar Dinajpur,0,0,...,43.8,38.5,14.3,3.3,1.6,330,3007134,2883,94.0,50.0

In [45]:
dta_cleaned = final_csv.loc[:, final_csv.columns != 'District code']

# Display the first few rows of the cleaned DataFrame
dta = dta_cleaned.to_csv('cleaned_data.csv', index=False)

In [47]:
dta_cleaned

,State,District,Latitude,Longitude,State Code,District Code,Tehsil Code,Tehsil Name,Town Code/Village code,Ward No,...,Contition_R_Total,Residence_Good,Residence_Livable,Residence_Dilapidated,Residence_cum_other,Residence_cum_Good,Population,Households_with_Internet,sex_ratio,literacy_rate
0,Andhra Pradesh,Adilabad,19.284514,78.813212,28,532,0,Adilabad,0,0,...,98.8,57.0,35.3,6.5,1.2,0.8,2741239,5512,100.0,54.0
1,Andhra Pradesh,Adilabad,19.284514,78.813212,28,532,0,Adilabad,0,0,...,98.6,61.2,31.9,5.5,1.4,0.9,2741239,5512,100.0,54.0
2,Andhra Pradesh,Adilabad,19.284514,78.813212,28,532,0,Adilabad,0,0,...,98.1,72.2,23.0,2.8,1.9,1.4,2741239,5512,100.0,54.0
3,Andhra Pradesh,Anantapur,14.312066,77.460158,28,553,0,Anantapur,0,0,...,97.6,73.6,21.0,2.9,2.4,1.7,4081148,8606,98.0,57.0
4,Andhra Pradesh,Anantapur,14.312066,77.460158,28,553,0,Anantapur,0,0,...,96.6,73.6,20.6,2.4,3.4,2.4,4081148,8606,98.0,57.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1702,West Bengal,Puruliya,23.254192,86.396853,19,340,0,Puruliya,0,0,...,93.1,30.7,55.5,6.9,6.9,1.7,2930115,3551,96.0,55.0
1703,West Bengal,Puruliya,23.254192,86.396853,19,340,0,Puruliya,0,0,...,95.8,47.9,41.4,6.5,4.2,2.0,2930115,3551,96.0,55.0
1704,West Bengal,Uttar Dinajpur,26.044619,88.235952,19,330,0,Uttar Dinajpur,0,0,...,97.3,29.1,56.1,12.1,2.7,0.7,3007134,2883,94.0,50.0
1705,West Bengal,Uttar Dinajpur,26.044619,88.235952,19,330,0,Uttar Dinajpur,0,0,...,97.3,30.8,54.1,12.4,2.7,0.8,3007134,2883,94.0,50.0
1706,West Bengal,Uttar Dinajpur,26.044619,88.235952,19,330,0,Uttar Dinajpur,0,0,...,96.7,43.8,38.5,14.3,3.3,1.6,3007134,2883,94.0,50.0